version: '3.8'

services:
  web:
    build: ./
    command: gunicorn docker_demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .//:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docker-demo
volumes:
  postgres_data: